config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :tools
  end

  namespace :admin do
    resources :tools, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tools
end

app/models/tool.rb
class Tool < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tools

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::BaseController
  def index
    @tools = Tool.all
    # require "pry"; binding.pry
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :most_recent_tool, :current_tool_summary, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def most_recent_tool
    User.find(current_user.id).tools.last
  end

  def current_tool_summary
    "<strong>Tools created this session: </strong>#{session[:current_tool_count]}
    <br><br>
     <strong>Total cost: </strong>#{session[:current_potential_revenue]}".html_safe
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have been logged in!"
      if current_admin?
        redirect_to admin_tools_path
      else
        redirect_to user_tools_path(user)
      end
    else
      flash[:danger] = "Invalid Login!"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_user, only: [:index, :new, :create, :edit, :update]


  def index
    @tools = @user.tools.all
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = @user.tools.new(tool_params)
    if @tool.save
      flash[:notice] = 'Tool created!'
      session[:current_tool_count] = 0 if session[:current_tool_count].nil?
      session[:current_tool_count] += @tool.quantity
      session[:current_potential_revenue] = 0.0 if session[:current_potential_revenue].nil?
      session[:current_potential_revenue] = session[:current_potential_revenue].to_f + @tool.price
      redirect_to user_tool_path(id: @tool)
    else
      flash.now[:error] = @tool.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to user_tool_path(id: @tool)
    else
      render :edit
    end
  end

  def destroy
    tool = Tool.find(params[:id])
    tool.destroy
    redirect_to user_tools_path
  end

private

  def set_user
    @user = User.find(current_user.id)
  end

  def tool_params
    params.require(:tool).permit(:name, :quantity, :price, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/tools/index.html.erb
<h1>All the Tools</h1>
<% @tools.each do |tool| %>
<h4><%= tool.name %> - <%= tool.quantity %> - $<%= tool.price %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToolChest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
     <div id="greeting"><%= "Hello, #{current_user.username}!" %></div>
    <% end %>

    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "flash_#{type}" %>
    <% end %>

    <%= yield %>

    <% if current_user %>
     <%= link_to "Sign Out", logout_path, method: :delete %>
    <% else %>
     <%= link_to "Sign In", login_path %>
    <% end %>
  </body>
</html>

app/views/shared/_summary.html.erb
<p><strong>Newest tool:</strong> <%= most_recent_tool.name if most_recent_tool %></p>
<p> <%= current_tool_summary %></p>

app/views/tools/edit.html.erb
<%= render partial: 'shared/summary' %>

<h1>Edit Tool</h1>
<%= form_for([@user, @tool]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :quantity %>
  <%= f.number_field :quantity %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/tools/index.html.erb
<%= render partial: 'shared/summary' %>

<h2>All the Tools</h2>

<div class="list_of_tools">
<% @tools.each do |tool| %>
<h4><%= link_to tool.name, user_tool_path(id: tool) %> - <%= tool.quantity %> - $<%= tool.price %></h4>
<%= link_to "Edit", edit_user_tool_path(id: tool) %>
<%= link_to "Delete", user_tool_path(id: tool), method: :delete %>
<% end %>
</div>
<br>
<%= link_to "Create New Tool", new_user_tool_path %>

app/views/tools/new.html.erb
<%= render partial: 'shared/summary' %>

<h1>Create Tool</h1>
<div class="tool_form">
<%= form_for([@user, @tool]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :quantity %>
  <%= f.number_field :quantity %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= collection_select(:tool, :category_id, Category.all, :id, :name) %>

  <%= f.submit %>
<% end %>
</div>

app/views/tools/show.html.erb
<%= render partial: 'shared/summary' %>

<div class="tool_info"><%= @tool.name %> - <%= @tool.quantity %> - <%= @tool.price %></div>
<br>
<%= link_to "Return Home", user_tools_path %>